name: Generate Snake Animation

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: brucelsprouts
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 